<?xml version="1.0" encoding="utf-8"?><Database Name="Identity" Class="ID_dataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:s11.winhost.com;Initial Catalog=DB_62333_identity;Integrated Security=False;User ID=DB_62333_identity_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Identity_Prod" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserList_vw" Member="UserList_vws">
    <Type Name="UserList_vw">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ValidateUser_vw" Member="ValidateUser_vws">
    <Type Name="ValidateUser_vw">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.UpdateLogin_Date" Method="UpdateLogin_Date">
    <Parameter Name="USER_NAME" Parameter="uSER_NAME" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.NewUser" Method="NewUser">
    <Parameter Name="USER_NAME" Parameter="uSER_NAME" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ROLE_NAME" Parameter="rOLE_NAME" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
</Database>