#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vMTS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_62333_devvmts")]
	public partial class vmts_dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNAME_SUFFIX(NAME_SUFFIX instance);
    partial void UpdateNAME_SUFFIX(NAME_SUFFIX instance);
    partial void DeleteNAME_SUFFIX(NAME_SUFFIX instance);
    partial void InsertRACE_LKP(RACE_LKP instance);
    partial void UpdateRACE_LKP(RACE_LKP instance);
    partial void DeleteRACE_LKP(RACE_LKP instance);
    partial void InserterrorLogging(errorLogging instance);
    partial void UpdateerrorLogging(errorLogging instance);
    partial void DeleteerrorLogging(errorLogging instance);
    #endregion
		
		public vmts_dataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["vMTS_Prod"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public vmts_dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vmts_dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vmts_dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vmts_dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NAME_SUFFIX> NAME_SUFFIXes
		{
			get
			{
				return this.GetTable<NAME_SUFFIX>();
			}
		}
		
		public System.Data.Linq.Table<Registration> Registrations
		{
			get
			{
				return this.GetTable<Registration>();
			}
		}
		
		public System.Data.Linq.Table<RACE_LKP> RACE_LKPs
		{
			get
			{
				return this.GetTable<RACE_LKP>();
			}
		}
		
		public System.Data.Linq.Table<Class_Schedule_view> Class_Schedule_views
		{
			get
			{
				return this.GetTable<Class_Schedule_view>();
			}
		}
		
		public System.Data.Linq.Table<errorLogging> errorLoggings
		{
			get
			{
				return this.GetTable<errorLogging>();
			}
		}
		
		public System.Data.Linq.Table<RegistrationCount> RegistrationCounts
		{
			get
			{
				return this.GetTable<RegistrationCount>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CancelClass")]
		public int CancelClass([global::System.Data.Linq.Mapping.ParameterAttribute(Name="C_ID", DbType="Int")] System.Nullable<int> c_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), c_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ClearSchedule")]
		public int ClearSchedule()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCarouselImage")]
		public int DeleteCarouselImage([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMG_id", DbType="Int")] System.Nullable<int> iMG_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iMG_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ConfirmRegistration")]
		public int ConfirmRegistration([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEIPT", DbType="BigInt")] System.Nullable<long> rECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rECEIPT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcessPayment")]
		public int ProcessPayment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEIPT", DbType="BigInt")] System.Nullable<long> rECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rECEIPT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CancelRegistration")]
		public ISingleResult<CancelRegistrationResult> CancelRegistration([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEIPT", DbType="BigInt")] System.Nullable<long> rECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rECEIPT);
			return ((ISingleResult<CancelRegistrationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SwitchClass")]
		public ISingleResult<SwitchClassResult> SwitchClass([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEIPT", DbType="BigInt")] System.Nullable<long> rECEIPT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OLD_CLASS", DbType="Int")] System.Nullable<int> oLD_CLASS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NEW_CLASS", DbType="Int")] System.Nullable<int> nEW_CLASS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rECEIPT, oLD_CLASS, nEW_CLASS);
			return ((ISingleResult<SwitchClassResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Class_Schedule_Changes")]
		public int Class_Schedule_Changes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="C_ID", DbType="Int")] System.Nullable<int> c_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="C_TYPE", DbType="NVarChar(150)")] string c_TYPE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="START", DbType="Date")] System.Nullable<System.DateTime> sTART, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="START_TIME", DbType="NVarChar(15)")] string sTART_TIME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="END", DbType="Date")] System.Nullable<System.DateTime> eND, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="END_TIME", DbType="NVarChar(15)")] string eND_TIME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LOCATION", DbType="NVarChar(150)")] string lOCATION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COURSE_NUMBER", DbType="Int")] System.Nullable<int> cOURSE_NUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OPEN_SEATS", DbType="Int")] System.Nullable<int> oPEN_SEATS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FEE", DbType="Money")] System.Nullable<decimal> fEE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), c_ID, c_TYPE, sTART, sTART_TIME, eND, eND_TIME, lOCATION, cOURSE_NUMBER, oPEN_SEATS, fEE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewRegistration")]
		public int NewRegistration(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="COURSE_ID", DbType="Int")] System.Nullable<int> cOURSE_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRSTNAME", DbType="VarChar(50)")] string fIRSTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIDDLENAME", DbType="NVarChar(50)")] string mIDDLENAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LASTNAME", DbType="VarChar(75)")] string lASTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUFFIX", DbType="NVarChar(10)")] string sUFFIX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS1", DbType="VarChar(150)")] string aDDRESS1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS2", DbType="VarChar(150)")] string aDDRESS2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CITY", DbType="VarChar(100)")] string cITY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATE", DbType="VarChar(2)")] string sTATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZIP", DbType="VarChar(5)")] string zIP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GDR", DbType="VarChar(1)")] string gDR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RACE", DbType="Int")] System.Nullable<int> rACE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHONE", DbType="VarChar(11)")] string pHONE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="VarChar(75)")] string eMAIL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOB", DbType="Date")] System.Nullable<System.DateTime> dOB, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AGE", DbType="Int")] System.Nullable<int> aGE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVAL", DbType="VarChar(1)")] string eVAL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOTOR_YR", DbType="VarChar(4)")] string mOTOR_YR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOTOR_MK", DbType="VarChar(20)")] string mOTOR_MK, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOTOR_MD", DbType="VarChar(20)")] string mOTOR_MD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DL_NUM", DbType="VarChar(50)")] string dL_NUM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DL_STATE", DbType="VarChar(2)")] string dL_STATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PMT_TYPE", DbType="VarChar(50)")] string pMT_TYPE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CARD_NAME", DbType="VarChar(150)")] string cARD_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CARD_NUM", DbType="VarChar(22)")] string cARD_NUM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EXP_MN", DbType="VarChar(2)")] string eXP_MN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EXP_YR", DbType="VarChar(4)")] string eXP_YR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CVV", DbType="VarChar(3)")] string cVV, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROMO", DbType="VarChar(10)")] string pROMO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROMO_VALUE", DbType="Money")] System.Nullable<decimal> pROMO_VALUE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEIPT", DbType="BigInt")] ref System.Nullable<long> rECEIPT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cOURSE_ID, fIRSTNAME, mIDDLENAME, lASTNAME, sUFFIX, aDDRESS1, aDDRESS2, cITY, sTATE, zIP, gDR, rACE, pHONE, eMAIL, dOB, aGE, eVAL, mOTOR_YR, mOTOR_MK, mOTOR_MD, dL_NUM, dL_STATE, pMT_TYPE, cARD_NAME, cARD_NUM, eXP_MN, eXP_YR, cVV, pROMO, pROMO_VALUE, rECEIPT);
			rECEIPT = ((System.Nullable<long>)(result.GetParameterValue(30)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRegistration", IsComposable=true)]
		public IQueryable<GetRegistrationResult> GetRegistration([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEIPT", DbType="BigInt")] System.Nullable<long> rECEIPT)
		{
			return this.CreateMethodCallQuery<GetRegistrationResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rECEIPT);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPayment", IsComposable=true)]
		public IQueryable<GetPaymentResult> GetPayment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEIPT_ID", DbType="BigInt")] System.Nullable<long> rECEIPT_ID)
		{
			return this.CreateMethodCallQuery<GetPaymentResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rECEIPT_ID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateRegistration")]
		public int UpdateRegistration(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STD_NUMBER", DbType="Int")] System.Nullable<int> sTD_NUMBER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS_ID", DbType="Int")] System.Nullable<int> aDDRESS_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PMT_ID", DbType="Int")] System.Nullable<int> pMT_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRSTNAME", DbType="VarChar(50)")] string fIRSTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIDDLE_NAME", DbType="NVarChar(50)")] string mIDDLE_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LASTNAME", DbType="VarChar(75)")] string lASTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUFFIX", DbType="NVarChar(10)")] string sUFFIX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS1", DbType="VarChar(150)")] string aDDRESS1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRESS2", DbType="VarChar(150)")] string aDDRESS2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CITY", DbType="VarChar(100)")] string cITY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATE", DbType="VarChar(2)")] string sTATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZIP", DbType="VarChar(5)")] string zIP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GENDER", DbType="VarChar(1)")] string gENDER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RACE", DbType="Int")] System.Nullable<int> rACE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHONE", DbType="VarChar(11)")] string pHONE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="VarChar(75)")] string eMAIL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOB", DbType="Date")] System.Nullable<System.DateTime> dOB, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AGE", DbType="Int")] System.Nullable<int> aGE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EVAL", DbType="VarChar(1)")] string eVAL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOTOR_YR", DbType="VarChar(4)")] string mOTOR_YR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOTOR_MK", DbType="VarChar(20)")] string mOTOR_MK, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOTOR_MD", DbType="VarChar(20)")] string mOTOR_MD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DL_NUM", DbType="VarChar(50)")] string dL_NUM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DL_ST", DbType="VarChar(2)")] string dL_ST, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PMT_TYPE", DbType="VarChar(50)")] string pMT_TYPE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CARD_NAME", DbType="VarChar(150)")] string cARD_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CARD_NUM", DbType="VarChar(22)")] string cARD_NUM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EXP_MN", DbType="VarChar(2)")] string eXP_MN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EXP_YR", DbType="VarChar(4)")] string eXP_YR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CVV", DbType="VarChar(3)")] string cVV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTD_NUMBER, aDDRESS_ID, pMT_ID, fIRSTNAME, mIDDLE_NAME, lASTNAME, sUFFIX, aDDRESS1, aDDRESS2, cITY, sTATE, zIP, gENDER, rACE, pHONE, eMAIL, dOB, aGE, eVAL, mOTOR_YR, mOTOR_MK, mOTOR_MD, dL_NUM, dL_ST, pMT_TYPE, cARD_NAME, cARD_NUM, eXP_MN, eXP_YR, cVV);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NAME_SUFFIX")]
	public partial class NAME_SUFFIX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SUFFIX_ABBR;
		
		private string _SUFFIX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSUFFIX_ABBRChanging(string value);
    partial void OnSUFFIX_ABBRChanged();
    partial void OnSUFFIXChanging(string value);
    partial void OnSUFFIXChanged();
    #endregion
		
		public NAME_SUFFIX()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUFFIX_ABBR", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SUFFIX_ABBR
		{
			get
			{
				return this._SUFFIX_ABBR;
			}
			set
			{
				if ((this._SUFFIX_ABBR != value))
				{
					this.OnSUFFIX_ABBRChanging(value);
					this.SendPropertyChanging();
					this._SUFFIX_ABBR = value;
					this.SendPropertyChanged("SUFFIX_ABBR");
					this.OnSUFFIX_ABBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUFFIX", DbType="VarChar(75)")]
		public string SUFFIX
		{
			get
			{
				return this._SUFFIX;
			}
			set
			{
				if ((this._SUFFIX != value))
				{
					this.OnSUFFIXChanging(value);
					this.SendPropertyChanging();
					this._SUFFIX = value;
					this.SendPropertyChanged("SUFFIX");
					this.OnSUFFIXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registrations")]
	public partial class Registration
	{
		
		private long _RECEIPT;
		
		private string _REG_DATE;
		
		private int _CLASS_ID;
		
		private string _CLASS_TYPE;
		
		private string _CLASS_DAY;
		
		private System.Nullable<System.DateTime> _CLASS_START_DATE;
		
		private System.Nullable<System.DateTime> _CLASS_END_DATE;
		
		private string _NAME;
		
		private string _SUFFIX;
		
		private string _ADDRESS;
		
		private string _CITY;
		
		private string _STATE;
		
		private string _ZIP;
		
		private string _GENDER;
		
		private string _RACE;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private System.Nullable<int> _AGE;
		
		private System.Data.Linq.Binary _DL_NUM;
		
		private System.Data.Linq.Binary _DL_ST;
		
		private int _PMT_ID;
		
		private System.Nullable<bool> _WAIVER;
		
		private string _EMAIL;
		
		private string _PHONE;
		
		private System.Nullable<System.TimeSpan> _CLASS_START_TIME;
		
		private System.Nullable<System.TimeSpan> _CLASS_END_TIME;
		
		private string _CLASS_LOCATION;
		
		private System.Nullable<int> _COURSE_NUMBER;
		
		private System.Nullable<bool> _VERBAL_FLAG;
		
		private int _STUDENT;
		
		private System.Nullable<bool> _CONFIRMED;
		
		private System.Nullable<System.DateTime> _CONFIRMED_DATE;
		
		private System.Nullable<bool> _PROCESSED;
		
		public Registration()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIPT", DbType="BigInt NOT NULL")]
		public long RECEIPT
		{
			get
			{
				return this._RECEIPT;
			}
			set
			{
				if ((this._RECEIPT != value))
				{
					this._RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_DATE", DbType="VarChar(25)")]
		public string REG_DATE
		{
			get
			{
				return this._REG_DATE;
			}
			set
			{
				if ((this._REG_DATE != value))
				{
					this._REG_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int NOT NULL")]
		public int CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this._CLASS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_TYPE", DbType="NVarChar(50)")]
		public string CLASS_TYPE
		{
			get
			{
				return this._CLASS_TYPE;
			}
			set
			{
				if ((this._CLASS_TYPE != value))
				{
					this._CLASS_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_DAY", DbType="NVarChar(30)")]
		public string CLASS_DAY
		{
			get
			{
				return this._CLASS_DAY;
			}
			set
			{
				if ((this._CLASS_DAY != value))
				{
					this._CLASS_DAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_START_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CLASS_START_DATE
		{
			get
			{
				return this._CLASS_START_DATE;
			}
			set
			{
				if ((this._CLASS_START_DATE != value))
				{
					this._CLASS_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_END_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CLASS_END_DATE
		{
			get
			{
				return this._CLASS_END_DATE;
			}
			set
			{
				if ((this._CLASS_END_DATE != value))
				{
					this._CLASS_END_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(177)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUFFIX", DbType="NVarChar(50)")]
		public string SUFFIX
		{
			get
			{
				return this._SUFFIX;
			}
			set
			{
				if ((this._SUFFIX != value))
				{
					this._SUFFIX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(301)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this._STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this._ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="NVarChar(1)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE", DbType="VarChar(75)")]
		public string RACE
		{
			get
			{
				return this._RACE;
			}
			set
			{
				if ((this._RACE != value))
				{
					this._RACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="Int")]
		public System.Nullable<int> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_NUM", DbType="VarBinary(8000)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DL_NUM
		{
			get
			{
				return this._DL_NUM;
			}
			set
			{
				if ((this._DL_NUM != value))
				{
					this._DL_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_ST", DbType="VarBinary(8000)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DL_ST
		{
			get
			{
				return this._DL_ST;
			}
			set
			{
				if ((this._DL_ST != value))
				{
					this._DL_ST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMT_ID", DbType="Int NOT NULL")]
		public int PMT_ID
		{
			get
			{
				return this._PMT_ID;
			}
			set
			{
				if ((this._PMT_ID != value))
				{
					this._PMT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAIVER", DbType="Bit")]
		public System.Nullable<bool> WAIVER
		{
			get
			{
				return this._WAIVER;
			}
			set
			{
				if ((this._WAIVER != value))
				{
					this._WAIVER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(75)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="NVarChar(14)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_START_TIME", DbType="Time")]
		public System.Nullable<System.TimeSpan> CLASS_START_TIME
		{
			get
			{
				return this._CLASS_START_TIME;
			}
			set
			{
				if ((this._CLASS_START_TIME != value))
				{
					this._CLASS_START_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_END_TIME", DbType="Time")]
		public System.Nullable<System.TimeSpan> CLASS_END_TIME
		{
			get
			{
				return this._CLASS_END_TIME;
			}
			set
			{
				if ((this._CLASS_END_TIME != value))
				{
					this._CLASS_END_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_LOCATION", DbType="VarChar(150)")]
		public string CLASS_LOCATION
		{
			get
			{
				return this._CLASS_LOCATION;
			}
			set
			{
				if ((this._CLASS_LOCATION != value))
				{
					this._CLASS_LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COURSE_NUMBER", DbType="Int")]
		public System.Nullable<int> COURSE_NUMBER
		{
			get
			{
				return this._COURSE_NUMBER;
			}
			set
			{
				if ((this._COURSE_NUMBER != value))
				{
					this._COURSE_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERBAL_FLAG", DbType="Bit")]
		public System.Nullable<bool> VERBAL_FLAG
		{
			get
			{
				return this._VERBAL_FLAG;
			}
			set
			{
				if ((this._VERBAL_FLAG != value))
				{
					this._VERBAL_FLAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT", DbType="Int NOT NULL")]
		public int STUDENT
		{
			get
			{
				return this._STUDENT;
			}
			set
			{
				if ((this._STUDENT != value))
				{
					this._STUDENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONFIRMED", DbType="Bit")]
		public System.Nullable<bool> CONFIRMED
		{
			get
			{
				return this._CONFIRMED;
			}
			set
			{
				if ((this._CONFIRMED != value))
				{
					this._CONFIRMED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONFIRMED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CONFIRMED_DATE
		{
			get
			{
				return this._CONFIRMED_DATE;
			}
			set
			{
				if ((this._CONFIRMED_DATE != value))
				{
					this._CONFIRMED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESSED", DbType="Bit")]
		public System.Nullable<bool> PROCESSED
		{
			get
			{
				return this._PROCESSED;
			}
			set
			{
				if ((this._PROCESSED != value))
				{
					this._PROCESSED = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RACE_LKP")]
	public partial class RACE_LKP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_ID;
		
		private string _RACE_CODE;
		
		private string _RACE_DESC;
		
		private System.Nullable<int> _sequence;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IDChanging(int value);
    partial void OnR_IDChanged();
    partial void OnRACE_CODEChanging(string value);
    partial void OnRACE_CODEChanged();
    partial void OnRACE_DESCChanging(string value);
    partial void OnRACE_DESCChanged();
    partial void OnsequenceChanging(System.Nullable<int> value);
    partial void OnsequenceChanged();
    #endregion
		
		public RACE_LKP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int R_ID
		{
			get
			{
				return this._R_ID;
			}
			set
			{
				if ((this._R_ID != value))
				{
					this.OnR_IDChanging(value);
					this.SendPropertyChanging();
					this._R_ID = value;
					this.SendPropertyChanged("R_ID");
					this.OnR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_CODE", DbType="VarChar(1)")]
		public string RACE_CODE
		{
			get
			{
				return this._RACE_CODE;
			}
			set
			{
				if ((this._RACE_CODE != value))
				{
					this.OnRACE_CODEChanging(value);
					this.SendPropertyChanging();
					this._RACE_CODE = value;
					this.SendPropertyChanged("RACE_CODE");
					this.OnRACE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE_DESC", DbType="VarChar(75)")]
		public string RACE_DESC
		{
			get
			{
				return this._RACE_DESC;
			}
			set
			{
				if ((this._RACE_DESC != value))
				{
					this.OnRACE_DESCChanging(value);
					this.SendPropertyChanging();
					this._RACE_DESC = value;
					this.SendPropertyChanged("RACE_DESC");
					this.OnRACE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sequence", DbType="Int")]
		public System.Nullable<int> sequence
		{
			get
			{
				return this._sequence;
			}
			set
			{
				if ((this._sequence != value))
				{
					this.OnsequenceChanging(value);
					this.SendPropertyChanging();
					this._sequence = value;
					this.SendPropertyChanged("sequence");
					this.OnsequenceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Class_Schedule_view")]
	public partial class Class_Schedule_view
	{
		
		private int _CLASS_ID;
		
		private string _CLASS_TYPE;
		
		private System.Nullable<System.DateTime> _CLASS_START_DATE;
		
		private System.Nullable<System.DateTime> _CLASS_END_DATE;
		
		private string _ClassDay;
		
		private string _CLASS_START_TIME;
		
		private string _CLASS_END_TIME;
		
		private System.Nullable<int> _OPEN_SEATS;
		
		private System.Nullable<decimal> _CLASS_FEE;
		
		private string _CLASS_LOCATION;
		
		private System.Nullable<int> _COURSE_NUMBER;
		
		private System.Nullable<System.TimeSpan> _ST_SELECTED;
		
		private System.Nullable<System.TimeSpan> _ET_SELECTED;
		
		private string _C1;
		
		private string _C2;
		
		public Class_Schedule_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int NOT NULL")]
		public int CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this._CLASS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_TYPE", DbType="NVarChar(50)")]
		public string CLASS_TYPE
		{
			get
			{
				return this._CLASS_TYPE;
			}
			set
			{
				if ((this._CLASS_TYPE != value))
				{
					this._CLASS_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_START_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CLASS_START_DATE
		{
			get
			{
				return this._CLASS_START_DATE;
			}
			set
			{
				if ((this._CLASS_START_DATE != value))
				{
					this._CLASS_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_END_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CLASS_END_DATE
		{
			get
			{
				return this._CLASS_END_DATE;
			}
			set
			{
				if ((this._CLASS_END_DATE != value))
				{
					this._CLASS_END_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDay", DbType="NVarChar(30)")]
		public string ClassDay
		{
			get
			{
				return this._ClassDay;
			}
			set
			{
				if ((this._ClassDay != value))
				{
					this._ClassDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_START_TIME", DbType="NVarChar(15)")]
		public string CLASS_START_TIME
		{
			get
			{
				return this._CLASS_START_TIME;
			}
			set
			{
				if ((this._CLASS_START_TIME != value))
				{
					this._CLASS_START_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_END_TIME", DbType="NVarChar(15)")]
		public string CLASS_END_TIME
		{
			get
			{
				return this._CLASS_END_TIME;
			}
			set
			{
				if ((this._CLASS_END_TIME != value))
				{
					this._CLASS_END_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPEN_SEATS", DbType="Int")]
		public System.Nullable<int> OPEN_SEATS
		{
			get
			{
				return this._OPEN_SEATS;
			}
			set
			{
				if ((this._OPEN_SEATS != value))
				{
					this._OPEN_SEATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_FEE", DbType="Money")]
		public System.Nullable<decimal> CLASS_FEE
		{
			get
			{
				return this._CLASS_FEE;
			}
			set
			{
				if ((this._CLASS_FEE != value))
				{
					this._CLASS_FEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_LOCATION", DbType="VarChar(150)")]
		public string CLASS_LOCATION
		{
			get
			{
				return this._CLASS_LOCATION;
			}
			set
			{
				if ((this._CLASS_LOCATION != value))
				{
					this._CLASS_LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COURSE_NUMBER", DbType="Int")]
		public System.Nullable<int> COURSE_NUMBER
		{
			get
			{
				return this._COURSE_NUMBER;
			}
			set
			{
				if ((this._COURSE_NUMBER != value))
				{
					this._COURSE_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_SELECTED", DbType="Time")]
		public System.Nullable<System.TimeSpan> ST_SELECTED
		{
			get
			{
				return this._ST_SELECTED;
			}
			set
			{
				if ((this._ST_SELECTED != value))
				{
					this._ST_SELECTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ET_SELECTED", DbType="Time")]
		public System.Nullable<System.TimeSpan> ET_SELECTED
		{
			get
			{
				return this._ET_SELECTED;
			}
			set
			{
				if ((this._ET_SELECTED != value))
				{
					this._ET_SELECTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C1", DbType="NVarChar(150)")]
		public string C1
		{
			get
			{
				return this._C1;
			}
			set
			{
				if ((this._C1 != value))
				{
					this._C1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C2", DbType="NVarChar(150)")]
		public string C2
		{
			get
			{
				return this._C2;
			}
			set
			{
				if ((this._C2 != value))
				{
					this._C2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.errorLogging")]
	public partial class errorLogging : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _logID;
		
		private string _logMethod;
		
		private string _logMessage;
		
		private string _logStackTrace;
		
		private System.Nullable<System.DateTime> _logDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlogIDChanging(int value);
    partial void OnlogIDChanged();
    partial void OnlogMethodChanging(string value);
    partial void OnlogMethodChanged();
    partial void OnlogMessageChanging(string value);
    partial void OnlogMessageChanged();
    partial void OnlogStackTraceChanging(string value);
    partial void OnlogStackTraceChanged();
    partial void OnlogDateChanging(System.Nullable<System.DateTime> value);
    partial void OnlogDateChanged();
    #endregion
		
		public errorLogging()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int logID
		{
			get
			{
				return this._logID;
			}
			set
			{
				if ((this._logID != value))
				{
					this.OnlogIDChanging(value);
					this.SendPropertyChanging();
					this._logID = value;
					this.SendPropertyChanged("logID");
					this.OnlogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logMethod", DbType="NVarChar(50)")]
		public string logMethod
		{
			get
			{
				return this._logMethod;
			}
			set
			{
				if ((this._logMethod != value))
				{
					this.OnlogMethodChanging(value);
					this.SendPropertyChanging();
					this._logMethod = value;
					this.SendPropertyChanged("logMethod");
					this.OnlogMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logMessage", DbType="NVarChar(150)")]
		public string logMessage
		{
			get
			{
				return this._logMessage;
			}
			set
			{
				if ((this._logMessage != value))
				{
					this.OnlogMessageChanging(value);
					this.SendPropertyChanging();
					this._logMessage = value;
					this.SendPropertyChanged("logMessage");
					this.OnlogMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logStackTrace", DbType="NVarChar(500)")]
		public string logStackTrace
		{
			get
			{
				return this._logStackTrace;
			}
			set
			{
				if ((this._logStackTrace != value))
				{
					this.OnlogStackTraceChanging(value);
					this.SendPropertyChanging();
					this._logStackTrace = value;
					this.SendPropertyChanged("logStackTrace");
					this.OnlogStackTraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> logDate
		{
			get
			{
				return this._logDate;
			}
			set
			{
				if ((this._logDate != value))
				{
					this.OnlogDateChanging(value);
					this.SendPropertyChanging();
					this._logDate = value;
					this.SendPropertyChanged("logDate");
					this.OnlogDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegistrationCount")]
	public partial class RegistrationCount
	{
		
		private int _CLASS_ID;
		
		private string _ClassDay;
		
		private System.Nullable<int> _REGISTRATIONS;
		
		private System.Nullable<int> _OPEN_SEATS;
		
		private System.Nullable<System.DateTime> _CLASS_START_DATE;
		
		private string _CLASS_TYPE;
		
		public RegistrationCount()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int NOT NULL")]
		public int CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this._CLASS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDay", DbType="NVarChar(30)")]
		public string ClassDay
		{
			get
			{
				return this._ClassDay;
			}
			set
			{
				if ((this._ClassDay != value))
				{
					this._ClassDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRATIONS", DbType="Int")]
		public System.Nullable<int> REGISTRATIONS
		{
			get
			{
				return this._REGISTRATIONS;
			}
			set
			{
				if ((this._REGISTRATIONS != value))
				{
					this._REGISTRATIONS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPEN_SEATS", DbType="Int")]
		public System.Nullable<int> OPEN_SEATS
		{
			get
			{
				return this._OPEN_SEATS;
			}
			set
			{
				if ((this._OPEN_SEATS != value))
				{
					this._OPEN_SEATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_START_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CLASS_START_DATE
		{
			get
			{
				return this._CLASS_START_DATE;
			}
			set
			{
				if ((this._CLASS_START_DATE != value))
				{
					this._CLASS_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_TYPE", DbType="NVarChar(50)")]
		public string CLASS_TYPE
		{
			get
			{
				return this._CLASS_TYPE;
			}
			set
			{
				if ((this._CLASS_TYPE != value))
				{
					this._CLASS_TYPE = value;
				}
			}
		}
	}
	
	public partial class CancelRegistrationResult
	{
		
		private System.Nullable<int> _ErrorNumber;
		
		private System.Nullable<int> _ErrorSeverity;
		
		private System.Nullable<int> _ErrorState;
		
		private string _ErrorProcedure;
		
		private System.Nullable<int> _ErrorLine;
		
		private string _ErrorMessage;
		
		public CancelRegistrationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorNumber", DbType="Int")]
		public System.Nullable<int> ErrorNumber
		{
			get
			{
				return this._ErrorNumber;
			}
			set
			{
				if ((this._ErrorNumber != value))
				{
					this._ErrorNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorSeverity", DbType="Int")]
		public System.Nullable<int> ErrorSeverity
		{
			get
			{
				return this._ErrorSeverity;
			}
			set
			{
				if ((this._ErrorSeverity != value))
				{
					this._ErrorSeverity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorState", DbType="Int")]
		public System.Nullable<int> ErrorState
		{
			get
			{
				return this._ErrorState;
			}
			set
			{
				if ((this._ErrorState != value))
				{
					this._ErrorState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorProcedure", DbType="NVarChar(128)")]
		public string ErrorProcedure
		{
			get
			{
				return this._ErrorProcedure;
			}
			set
			{
				if ((this._ErrorProcedure != value))
				{
					this._ErrorProcedure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLine", DbType="Int")]
		public System.Nullable<int> ErrorLine
		{
			get
			{
				return this._ErrorLine;
			}
			set
			{
				if ((this._ErrorLine != value))
				{
					this._ErrorLine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class SwitchClassResult
	{
		
		private System.Nullable<int> _ErrorNumber;
		
		private System.Nullable<int> _ErrorSeverity;
		
		private System.Nullable<int> _ErrorState;
		
		private string _ErrorProcedure;
		
		private System.Nullable<int> _ErrorLine;
		
		private string _ErrorMessage;
		
		public SwitchClassResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorNumber", DbType="Int")]
		public System.Nullable<int> ErrorNumber
		{
			get
			{
				return this._ErrorNumber;
			}
			set
			{
				if ((this._ErrorNumber != value))
				{
					this._ErrorNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorSeverity", DbType="Int")]
		public System.Nullable<int> ErrorSeverity
		{
			get
			{
				return this._ErrorSeverity;
			}
			set
			{
				if ((this._ErrorSeverity != value))
				{
					this._ErrorSeverity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorState", DbType="Int")]
		public System.Nullable<int> ErrorState
		{
			get
			{
				return this._ErrorState;
			}
			set
			{
				if ((this._ErrorState != value))
				{
					this._ErrorState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorProcedure", DbType="NVarChar(128)")]
		public string ErrorProcedure
		{
			get
			{
				return this._ErrorProcedure;
			}
			set
			{
				if ((this._ErrorProcedure != value))
				{
					this._ErrorProcedure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLine", DbType="Int")]
		public System.Nullable<int> ErrorLine
		{
			get
			{
				return this._ErrorLine;
			}
			set
			{
				if ((this._ErrorLine != value))
				{
					this._ErrorLine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class GetRegistrationResult
	{
		
		private System.Nullable<int> _CLASS_ID;
		
		private System.Nullable<int> _STUDENT_ID;
		
		private string _CLASS_DAY;
		
		private string _CLASS_TYPE;
		
		private string _FIRSTNAME;
		
		private string _MIDDLENAME;
		
		private string _LASTNAME;
		
		private string _SUFFIX;
		
		private string _PHONE;
		
		private string _GENDER;
		
		private string _DOB;
		
		private string _RACE;
		
		private string _EMAIL;
		
		private string _ADDRESS1;
		
		private string _ADDRESS2;
		
		private string _CITY;
		
		private string _STATE;
		
		private string _STATE_NAME;
		
		private string _ZIP;
		
		private string _DL_ST;
		
		private string _DL_NUM;
		
		private string _EVAL;
		
		private string _MOTOR_YR;
		
		private string _MOTOR_MK;
		
		private string _MOTOR_MD;
		
		private System.Nullable<long> _RECEIPT;
		
		private string _REG_DATE;
		
		private System.Nullable<bool> _CONFIRMED;
		
		private string _CONFIRMED_DATE;
		
		private System.Nullable<int> _AGE;
		
		private System.Nullable<int> _ADDRESS_ID;
		
		public GetRegistrationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int")]
		public System.Nullable<int> CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this._CLASS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT_ID", DbType="Int")]
		public System.Nullable<int> STUDENT_ID
		{
			get
			{
				return this._STUDENT_ID;
			}
			set
			{
				if ((this._STUDENT_ID != value))
				{
					this._STUDENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_DAY", DbType="VarChar(75)")]
		public string CLASS_DAY
		{
			get
			{
				return this._CLASS_DAY;
			}
			set
			{
				if ((this._CLASS_DAY != value))
				{
					this._CLASS_DAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_TYPE", DbType="NVarChar(150)")]
		public string CLASS_TYPE
		{
			get
			{
				return this._CLASS_TYPE;
			}
			set
			{
				if ((this._CLASS_TYPE != value))
				{
					this._CLASS_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(75)")]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIDDLENAME", DbType="VarChar(50)")]
		public string MIDDLENAME
		{
			get
			{
				return this._MIDDLENAME;
			}
			set
			{
				if ((this._MIDDLENAME != value))
				{
					this._MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(75)")]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUFFIX", DbType="VarChar(7)")]
		public string SUFFIX
		{
			get
			{
				return this._SUFFIX;
			}
			set
			{
				if ((this._SUFFIX != value))
				{
					this._SUFFIX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="VarChar(15)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(10)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="VarChar(10)")]
		public string DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RACE", DbType="VarChar(50)")]
		public string RACE
		{
			get
			{
				return this._RACE;
			}
			set
			{
				if ((this._RACE != value))
				{
					this._RACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(75)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS1", DbType="VarChar(150)")]
		public string ADDRESS1
		{
			get
			{
				return this._ADDRESS1;
			}
			set
			{
				if ((this._ADDRESS1 != value))
				{
					this._ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS2", DbType="VarChar(75)")]
		public string ADDRESS2
		{
			get
			{
				return this._ADDRESS2;
			}
			set
			{
				if ((this._ADDRESS2 != value))
				{
					this._ADDRESS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(75)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="VarChar(2)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this._STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STATE NAME]", Storage="_STATE_NAME", DbType="VarChar(50)")]
		public string STATE_NAME
		{
			get
			{
				return this._STATE_NAME;
			}
			set
			{
				if ((this._STATE_NAME != value))
				{
					this._STATE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="VarChar(5)")]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this._ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_ST", DbType="VarChar(255)")]
		public string DL_ST
		{
			get
			{
				return this._DL_ST;
			}
			set
			{
				if ((this._DL_ST != value))
				{
					this._DL_ST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DL_NUM", DbType="VarChar(255)")]
		public string DL_NUM
		{
			get
			{
				return this._DL_NUM;
			}
			set
			{
				if ((this._DL_NUM != value))
				{
					this._DL_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVAL", DbType="NVarChar(1)")]
		public string EVAL
		{
			get
			{
				return this._EVAL;
			}
			set
			{
				if ((this._EVAL != value))
				{
					this._EVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTOR_YR", DbType="NVarChar(4)")]
		public string MOTOR_YR
		{
			get
			{
				return this._MOTOR_YR;
			}
			set
			{
				if ((this._MOTOR_YR != value))
				{
					this._MOTOR_YR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTOR_MK", DbType="NVarChar(20)")]
		public string MOTOR_MK
		{
			get
			{
				return this._MOTOR_MK;
			}
			set
			{
				if ((this._MOTOR_MK != value))
				{
					this._MOTOR_MK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTOR_MD", DbType="NVarChar(20)")]
		public string MOTOR_MD
		{
			get
			{
				return this._MOTOR_MD;
			}
			set
			{
				if ((this._MOTOR_MD != value))
				{
					this._MOTOR_MD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIPT", DbType="BigInt")]
		public System.Nullable<long> RECEIPT
		{
			get
			{
				return this._RECEIPT;
			}
			set
			{
				if ((this._RECEIPT != value))
				{
					this._RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG_DATE", DbType="NVarChar(35)")]
		public string REG_DATE
		{
			get
			{
				return this._REG_DATE;
			}
			set
			{
				if ((this._REG_DATE != value))
				{
					this._REG_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONFIRMED", DbType="Bit")]
		public System.Nullable<bool> CONFIRMED
		{
			get
			{
				return this._CONFIRMED;
			}
			set
			{
				if ((this._CONFIRMED != value))
				{
					this._CONFIRMED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONFIRMED_DATE", DbType="NVarChar(35)")]
		public string CONFIRMED_DATE
		{
			get
			{
				return this._CONFIRMED_DATE;
			}
			set
			{
				if ((this._CONFIRMED_DATE != value))
				{
					this._CONFIRMED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="Int")]
		public System.Nullable<int> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_ID", DbType="Int")]
		public System.Nullable<int> ADDRESS_ID
		{
			get
			{
				return this._ADDRESS_ID;
			}
			set
			{
				if ((this._ADDRESS_ID != value))
				{
					this._ADDRESS_ID = value;
				}
			}
		}
	}
	
	public partial class GetPaymentResult
	{
		
		private System.Nullable<long> _RECEIPT;
		
		private string _PMT_TYPE;
		
		private string _CARDNAME;
		
		private string _CARDNUMBER;
		
		private string _CARD_EXP;
		
		private string _CARD_EXP_YR;
		
		private string _CVV;
		
		private System.Nullable<bool> _PROCESSED;
		
		private string _STUFF_CARDNUMBER;
		
		private string _STUFF_CARD_EXP;
		
		private string _STUFF_CARD_EXP_YR;
		
		private string _STUFF_CVV;
		
		private string _PROMOCODE;
		
		private System.Nullable<decimal> _CLASS_FEE;
		
		private System.Nullable<decimal> _PROMO_VALUE;
		
		private System.Nullable<decimal> _TOTAL;
		
		private System.Nullable<System.DateTime> _PROCESSED_DATE;
		
		private System.Nullable<int> _PMT_ID;
		
		public GetPaymentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIPT", DbType="BigInt")]
		public System.Nullable<long> RECEIPT
		{
			get
			{
				return this._RECEIPT;
			}
			set
			{
				if ((this._RECEIPT != value))
				{
					this._RECEIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMT_TYPE", DbType="VarChar(100)")]
		public string PMT_TYPE
		{
			get
			{
				return this._PMT_TYPE;
			}
			set
			{
				if ((this._PMT_TYPE != value))
				{
					this._PMT_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARDNAME", DbType="VarChar(150)")]
		public string CARDNAME
		{
			get
			{
				return this._CARDNAME;
			}
			set
			{
				if ((this._CARDNAME != value))
				{
					this._CARDNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARDNUMBER", DbType="VarChar(100)")]
		public string CARDNUMBER
		{
			get
			{
				return this._CARDNUMBER;
			}
			set
			{
				if ((this._CARDNUMBER != value))
				{
					this._CARDNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARD_EXP", DbType="VarChar(100)")]
		public string CARD_EXP
		{
			get
			{
				return this._CARD_EXP;
			}
			set
			{
				if ((this._CARD_EXP != value))
				{
					this._CARD_EXP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARD_EXP_YR", DbType="VarChar(100)")]
		public string CARD_EXP_YR
		{
			get
			{
				return this._CARD_EXP_YR;
			}
			set
			{
				if ((this._CARD_EXP_YR != value))
				{
					this._CARD_EXP_YR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVV", DbType="VarChar(100)")]
		public string CVV
		{
			get
			{
				return this._CVV;
			}
			set
			{
				if ((this._CVV != value))
				{
					this._CVV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESSED", DbType="Bit")]
		public System.Nullable<bool> PROCESSED
		{
			get
			{
				return this._PROCESSED;
			}
			set
			{
				if ((this._PROCESSED != value))
				{
					this._PROCESSED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUFF_CARDNUMBER", DbType="VarChar(100)")]
		public string STUFF_CARDNUMBER
		{
			get
			{
				return this._STUFF_CARDNUMBER;
			}
			set
			{
				if ((this._STUFF_CARDNUMBER != value))
				{
					this._STUFF_CARDNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUFF_CARD_EXP", DbType="VarChar(100)")]
		public string STUFF_CARD_EXP
		{
			get
			{
				return this._STUFF_CARD_EXP;
			}
			set
			{
				if ((this._STUFF_CARD_EXP != value))
				{
					this._STUFF_CARD_EXP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUFF_CARD_EXP_YR", DbType="VarChar(100)")]
		public string STUFF_CARD_EXP_YR
		{
			get
			{
				return this._STUFF_CARD_EXP_YR;
			}
			set
			{
				if ((this._STUFF_CARD_EXP_YR != value))
				{
					this._STUFF_CARD_EXP_YR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUFF_CVV", DbType="VarChar(100)")]
		public string STUFF_CVV
		{
			get
			{
				return this._STUFF_CVV;
			}
			set
			{
				if ((this._STUFF_CVV != value))
				{
					this._STUFF_CVV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMOCODE", DbType="VarChar(100)")]
		public string PROMOCODE
		{
			get
			{
				return this._PROMOCODE;
			}
			set
			{
				if ((this._PROMOCODE != value))
				{
					this._PROMOCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_FEE", DbType="Money")]
		public System.Nullable<decimal> CLASS_FEE
		{
			get
			{
				return this._CLASS_FEE;
			}
			set
			{
				if ((this._CLASS_FEE != value))
				{
					this._CLASS_FEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROMO_VALUE", DbType="Money")]
		public System.Nullable<decimal> PROMO_VALUE
		{
			get
			{
				return this._PROMO_VALUE;
			}
			set
			{
				if ((this._PROMO_VALUE != value))
				{
					this._PROMO_VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Money")]
		public System.Nullable<decimal> TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESSED_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> PROCESSED_DATE
		{
			get
			{
				return this._PROCESSED_DATE;
			}
			set
			{
				if ((this._PROCESSED_DATE != value))
				{
					this._PROCESSED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMT_ID", DbType="Int")]
		public System.Nullable<int> PMT_ID
		{
			get
			{
				return this._PMT_ID;
			}
			set
			{
				if ((this._PMT_ID != value))
				{
					this._PMT_ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
